version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/London"
    groups:
      packages:
        patterns:
          - "*"
    labels:
      - ":game_die: dependencies"
      - ":robot: bot"
    
