name: 'pkgchk'
description: 'An Action for .Net package dependency checks & PRs.'
author: "tonycknight"
inputs:
  project-path:  
    description: 'The relative path to the solution or project'
    required: true  
  scan-issues:
    description: 'Scan for vulnerable, transitive or deprecated packages'
    required: false
    default: true
  scan-upgrades:
    description: 'Scan for package upgrades'
    required: false
    default: false
  deprecated:  
    description: 'Include deprecated packages in scans'
    required: false
    default: false    
  vulnerable: 
    description: 'Include vulnerable packages in scans'
    required: false
    default: true
  transitives: 
    description: 'Include transitive packages in scans'
    required: false
    default: true
  trace: 
    description: 'Output trace'
    required: false
    default: false
  github-token: 
    description: 'Github token'
    required: true
    default: ${{ github.token }}
  repo: 
    description: 'The repository name, as owner/repo'
    required: false
    default: ${{ github.repository }}
  github-title: 
    description: 'The vulnerability report title'
    required: false
    default: 'Package vulnerabilities'
  github-upgrade-title: 
    description: 'The upgrades report title'
    required: false
    default: 'Package upgrades'
  prid: 
    description: 'The pull request ID'
    required: false
    default: ${{ github.event.number }}
  commit-hash: 
    description: 'The commit hash'
    required: false
    default: ${{ github.sha }}
  fail-on-critical: 
    description: 'fail on Critical severity vulnerabilities and packages deprecated for Critical Bugs reasons'
    required: true
    default: true
  fail-on-high: 
    description: 'fail on High severity vulnerabilities'
    required: true
    default: true
  fail-on-moderate: 
    description: 'fail on Moderate severity vulnerabilities'
    required: true
    default: false
  fail-on-legacy: 
    description: 'fail on packages deprecated for Legacy reasons, such as package deprecation.'
    required: true
    default: false
  fail-on-upgrades: 
    description: 'fail on any outstanding package upgrades.'
    required: true
    default: false
  pass-img: 
    description: 'URI of an image for successful scans'
    required: false
    default: ''
  fail-img: 
    description: 'URI of an image for failed scans'
    required: false
    default: ''
  restore-solution: 
    description: 'Restore solution'
    required: false
    default: true
  restore-tools: 
    description: 'Restore tools'
    required: false
    default: true
runs:  
      using: 'composite'
      steps:
        - name: Restore tools
          shell: bash
          if: ${{ inputs.restore-tools == 'true' }}
          run: dotnet tool restore
            
        - name: Restore solution
          shell: bash
          if: ${{ inputs.restore-solution == 'true' }}
          run: dotnet restore ./${{ inputs.project-path }}

        - name: Install tool 
          shell: bash
          run: dotnet tool install pkgchk-cli --version 0.3.558-preview --local  --create-manifest-if-needed
          
        - name: Scan for vulnerabilities
          id: scanVulnerabilities
          shell: bash
          if: ${{ inputs.scan-issues == 'true' }}
          continue-on-error: true # TODO: this causes the overall flow to NOT be marked as failed.
          run: |
            dotnet pkgchk scan ./${{ inputs.project-path }} --deprecated ${{ inputs.deprecated }} --vulnerable ${{ inputs.vulnerable }} --transitive ${{ inputs.transitives }} --trace ${{ inputs.trace }} --github-token ${{ inputs.github-token }} --github-repo ${{ inputs.repo }}  --github-commit ${{ inputs.commit-hash }} --github-title "${{ inputs.github-title }}" --pass-img "${{ inputs.pass-img }}" --fail-img "${{ inputs.fail-img }}"  --github-pr "${{ inputs.prid }}" -s "${{ inputs.fail-on-critical == 'true' && 'Critical' || ' ' }}" -s "${{ inputs.fail-on-high == 'true' && 'High' || ' ' }}" -s "${{ inputs.fail-on-moderate == 'true' && 'Moderate' || ' ' }}" -s "${{ inputs.fail-on-critical == 'true' && 'Critical Bugs' || ' ' }}"  -s "${{ inputs.fail-on-legacy == 'true' && 'Legacy' || ' ' }}"

        - name: Scan for upgrades
          id: scanUpgrades
          shell: bash
          if: ${{ inputs.scan-upgrades == 'true' }}
          continue-on-error: true # TODO: this causes the overall flow to NOT be marked as failed.
          run: |
            dotnet pkgchk upgrades ./${{ inputs.project-path }} --trace ${{ inputs.trace }} --github-token ${{ inputs.github-token }} --github-repo ${{ inputs.repo }}  --github-commit ${{ inputs.commit-hash }} --github-title "${{ inputs.github-upgrade-title }}" --pass-img "${{ inputs.pass-img }}" --fail-img "${{ inputs.fail-img }}"  --github-pr "${{ inputs.prid }}" --break-on-upgrades "${{ inputs.fail-on-upgrades }}"

        - name: Consolidate results
          if : steps.scanVulnerabilities.outcome == 'failure' || steps.scanUpgrades.outcome == 'failure'
          shell: bash
          run: exit 1

branding:
  icon: 'shield'
  color: 'green'
      
