name: Release

on:
  push:
    tags:        
      - '*'           # Push events to every tag not containing /
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/**'
      - '**/*.md'
      - '*.md'
  workflow_dispatch:
  
jobs:
  
  gh-release:
    name: Github release
    runs-on: ubuntu-latest
    
    steps:    
      - uses: actions/checkout@v4
      
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          prerelease: false
          generateReleaseNotes: true